parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: jeu_ecoledemagie
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 862b7367cc69b5ed2f4d6d83e3813f03cf1e2d7b
    database_path: null
