parameters:
#    ecole_de_magie_jeu.example.class: EcoleDeMagie\JeuBundle\Example

services:
#    ecole_de_magie_jeu.example:
#        class: %ecole_de_magie_jeu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
