parameters:
#    ecole_de_magie_download.example.class: EcoleDeMagie\DownloadBundle\Example

services:
#    ecole_de_magie_download.example:
#        class: %ecole_de_magie_download.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
