parameters:
#    ecole_de_magie_user.example.class: EcoleDeMagie\UserBundle\Example

services:
#    ecole_de_magie_user.example:
#        class: %ecole_de_magie_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
