parameters:
#    ecole_de_magie_online.example.class: EcoleDeMagie\OnlineBundle\Example

services:
#    ecole_de_magie_online.example:
#        class: %ecole_de_magie_online.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
