parameters:
#    ecole_de_magie_desktop.example.class: EcoleDeMagie\DesktopBundle\Example

services:
#    ecole_de_magie_desktop.example:
#        class: %ecole_de_magie_desktop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
